## Manejo de Arreglos

In [1]:
# Importando librerias para manejo de arrays y para plotear
import numpy as np

In [2]:
# Creando mi primer array unidimensional
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Creando mi array bidimensional
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# Creando un arreglo unidimensional de unos
uni_ones = np.ones(shape=[5],dtype=np.int)
print(uni_ones)
# Creando un arreglo unidimensional de unos
bi_ones = np.ones(shape=[5,4],dtype=np.int)
print(bi_ones)

[1 1 1 1 1]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
# Imprimiendo las dimensiones
print(uni_ones.shape)
print(bi_ones.shape)

(5,)
(5, 4)


In [7]:
# Creando un arreglo bidimensional random (valores entre 0 y 1)
bi_random = np.random.random([2,3])
print(bi_random)

[[ 0.4071631   0.71258966  0.22802354]
 [ 0.38284035  0.00308013  0.28536741]]


### Operaciones en un arreglo

In [8]:
#suma
print(bi_random.sum())
print(bi_random.sum(axis=0)) #por columna
print(bi_random.sum(axis=1)) #por fila

2.01906419589
[ 0.79000345  0.71566979  0.51339095]
[ 1.34777631  0.67128789]


In [24]:
# Otras operaciones
print(bi_random.mean()) #media
print(bi_random.std()) #desviación estándar

0.685637909329
0.283808612631


### Operaciones entre arreglos

In [28]:
# Multiplicación entre arreglos unidimensionales
x = np.array([1,2])
y = np.array([5,6])
print(np.dot(x,y))
print(np.outer(x,y))

17
[[ 5  6]
 [10 12]]


In [34]:
# Multiplicación entre arreglos bidimensionales
bi_x = np.array([[1,2,3],[3,4,5]])
bi_y = np.array([[1,1,1],[2,2,2]])
bi_y_dot = np.array([[1,1],[2,2],[3,3]])
print(np.dot(bi_x, bi_y_dot))
print(np.outer(bi_x, bi_y))

[[14 14]
 [26 26]]
[[ 1  1  1  2  2  2]
 [ 2  2  2  4  4  4]
 [ 3  3  3  6  6  6]
 [ 3  3  3  6  6  6]
 [ 4  4  4  8  8  8]
 [ 5  5  5 10 10 10]]


In [35]:
m = np.array([1,2,3,4,5,5,6,3,2])
np.unique(m)

array([1, 2, 3, 4, 5, 6])

In [36]:
'''Ejercicio

Halle los siguientes datos del dataset
Numero de muestras por clase (digito)
Valor minimo, maximo, media y varianza entre valores de pixel del dataset 
	para todo
	para cada clase
'''	

'Ejercicio\n\nHalle los siguientes datos del dataset\nNumero de muestras por clase (digito)\nValor minimo, maximo, media y varianza entre valores de pixel del dataset \n\tpara todo\n\tpara cada clase\n'

In [9]:
from sklearn import datasets

In [10]:
digits = datasets.load_digits()

In [15]:
X = digits.data
y = digits.target #clase números de 0 a 9

In [26]:
for digit in np.unique(y):
    X_dig = X[digit == y]
    print(digit, "\t", X_dig.shape[0], "\t", X_dig.min(), "\t", X_dig.max(), "\t", X_dig.mean(), "\t", X_dig.std())

0 	 178 	 0.0 	 16.0 	 4.95215941011 	 5.72796620204
1 	 182 	 0.0 	 16.0 	 4.89414491758 	 6.41000195465
2 	 177 	 0.0 	 16.0 	 4.90519067797 	 6.07589545193
3 	 183 	 0.0 	 16.0 	 4.79431352459 	 5.94533026447
4 	 181 	 0.0 	 16.0 	 4.85488604972 	 6.07305506979
5 	 182 	 0.0 	 16.0 	 4.80039491758 	 5.95239902075
6 	 181 	 0.0 	 16.0 	 4.86325966851 	 6.03660138036
7 	 179 	 0.0 	 16.0 	 4.73891410615 	 6.01702725416
8 	 174 	 0.0 	 16.0 	 5.15517241379 	 6.02019964004
9 	 180 	 0.0 	 16.0 	 4.89513888889 	 5.87199485625


In [28]:
0 == y

array([ True, False, False, ..., False, False, False], dtype=bool)